#!bin/bash

echo -e "\e[32mSeleccione Una Opcion:\e[0m"
           select yn in "1)Instalar VPS" "2)Configurar VPS/Puertos/Etc" "3)Usuarios" "4)Cerrar"; do
             case $yn in
                   "1) Instalar VPS") bash Instalacion ; exit;;
                   "2) Configurar VPS/Puertos/Etc") bash expiracion ; exit;;
                    "3) Usuarios")  ; exit;;
                    "4) Cerrar") exit ;;
esac
done
