#!bin/bash
echo -e "\e[41m CONSOLA VPS-ARG By:Sharklight:\e[0m"

echo -e "\e[32mSeleccione Una Opcion:\e[0m"
           select yn in "Instalar VPS" "Configurar VPS/Puertos/Etc" "Usuarios" "Cerrar"; do
             case $yn in
                   "Instalar VPS") bash Instalacion ; exit;;
                    "Configurar VPS/Puertos/Etc") bash Configuracion ; exit;;
                    "Usuarios") bash menuuser; exit;;
                    "Cerrar") exit ;;
esac
done
