#!/bin/bash
sleep 3; echo 🄰🅄🅃🄾🅂🅃🄰🅁🅃
sleep 3; echo -e "\e[31mIniciando BadVpn\e[0m"
sleep 3; badvpn start 
sleep 3; echo -e "\e[32mInicio Exitoso\e[0m"
sleep 3; echo -e "\e[31mIniciando Dropbear\e[0m"
sleep 3; nohup bash /etc/dropbear/run & 
sleep 3; echo -e "\e[32mInicio Exitoso\e[0m"
sleep 3; echo -e "\e[31mIniciando ProxyAbono\e[0m"
sleep 3; nohup python Proxypython.py &
sleep 3; echo -e "\e[32mInicio Exitoso\e[0m"
sleep 3 ;echo -e "\e[31mCerrando en...\e[0m"
sleep 3 ;echo -e "\e[31m3.\e[0m"
sleep 3 ;echo -e "\e[31m2\e[0m"
sleep 3 ;echo -e "\e[31m1\e[0m"
