#!/bin/bash
echo -e "\e[106m Menu De configuracion\e[0m"
 select yn in "Dropbear" "Proxy Abono" "BADVPN (Solo si falla)" "Volver al menu principal" ; do
             case $yn in
                   "Dropbear") sleep 3 ; echo -e "\e[32mSi eres de android cambia el puerto por 8022!\e[0m";sleep 2 ; echo -e "\e[32mSi no lo eres pon el puerto 443 y guarda los cambios\e[0m" ;
sleep 6 ; nano /etc/dropbear/run ; echo Finalizado ; sleep 1 ; echo -e "\e[7mEl Dropbear ha sido configurado!\e[0m" ; break ; bash Configuracion;;
                   "Proxy Abono") sleep 3 ; echo -e "\e[7mComenzando Configuracion del proxy abono!\e[0m"  
sleep 2 ; echo -e "\e[32mRecuerda solo modificar las ip y los nombres!\e[0m" ;sleep 2 ; nano Proxypython.py ;
sleep 3 ; echo -e "\e[7mCorrecto!\e[0m" ; bash Configuracion ;;
                     "BADVPN (Solo si falla)")apt-get install cmake ; apt-get install make ; wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2 ; tar xf badvpn-1.999.128.tar.bz2 ; cd badvpn-1.999.128/ ; cmake ~/badvpn-1.999.128 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 ; make install
badvpn-udpgw --listen-addr 127.0.0.1:7300 > /dev/null & cd /etc/ ; wget https://raw.githubusercontent.com/nachorivas581/ARCHIVOSVPS/main/rc.local ; cd ; bash adm

                    "Volver al menu principal") bash adm ; exit;;
esac
done

