#!/bin/bash
echo "░██████╗██╗░░██╗░█████╗░██████╗░██╗░░██╗██╗░░░██╗██████╗░░██████╗";
echo "██╔════╝██║░░██║██╔══██╗██╔══██╗██║░██╔╝██║░░░██║██╔══██╗██╔════╝";
echo "╚█████╗░███████║███████║██████╔╝█████═╝░╚██╗░██╔╝██████╔╝╚█████╗░";
echo  "╚═══██╗██╔══██║██╔══██║██╔══██╗██╔═██╗░░╚████╔╝░██╔═══╝░░╚═══██╗";
echo "██████╔╝██║░░██║██║░░██║██║░░██║██║░╚██╗░░╚██╔╝░░██║░░░░░██████╔╝";
echo "╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚═════╝░";

sleep 3 ; echo -e "\e[7mComenzando Configuraciones!\e[0m" ; sleep 3 ; echo -e "\e[32mSi eres de android cambia el puerto por 8022!\e[0m";sleep 2 ; echo -e "\e[32mSi no lo eres pon el puerto 443 y guarda los cambios\e[0m"
sleep 6 ; nano /etc/dropbear/run ; echo Finalizado
sleep 2 ; echo "En caso de que no este activado el dropbear  ubica el  NO_START:1 y Cambialo por NO_START:0 Y GUARDA LA CONFIGURACION"
sleep 3 ;nano /etc/init.d/dropbear ; echo  Finalizado
sleep 1 ; echo -e "\e[7mEl Dropbear ha sido configurado!\e[0m"
sleep 3 ; echo -e "\e[7mComenzando Configuracion del proxy abono!\e[0m"  
sleep 2 ; echo -e "\e[32mRecuerda solo modificar las ip y los nombres!\e[0m" 
sleep 2 ; nano Proxypython.py
sleep 3 ; echo -e"\e[7mCorrecto!\e[0m"
