#!/bin/bash
echo "░██████╗██╗░░██╗░█████╗░██████╗░██╗░░██╗██╗░░░██╗██████╗░░██████╗";
echo "██╔════╝██║░░██║██╔══██╗██╔══██╗██║░██╔╝██║░░░██║██╔══██╗██╔════╝";
echo "╚█████╗░███████║███████║██████╔╝█████═╝░╚██╗░██╔╝██████╔╝╚█████╗░";
echo  "╚═══██╗██╔══██║██╔══██║██╔══██╗██╔═██╗░░╚████╔╝░██╔═══╝░░╚═══██╗";
echo "██████╔╝██║░░██║██║░░██║██║░░██║██║░╚██╗░░╚██╔╝░░██║░░░░░██████╔╝";
echo "╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚═════╝░";


sleep 2 ; echo Recuerda que necesitamos que nos concedas permisos de SuperUsuario para Continuar ;
sleep 2 ; echo -e "\e[91mSi no tienes Dichos Permisos Tendras errores en la instalacion!\e[0m"
sleep 2 ; echo "Muchas Gracias"
sleep 3; echo Estamos actualizando la consola &&
sleep 2;apt update -y ; apt upgrade -y ; apt install nano 
sleep 3;echo -e "\e[32mEXITO!\e[0m" ; 
sleep 3 ; echo -e "\e[106mInstalaremos los archivos necesarios!\e[0m"
sleep 3 ;echo -e "\e[101mBuscando Archivos!\e[0m"
sleep 3 ;echo -e "\e[7mPermisos concedidos!\e[0m"
sleep 6 ;echo -e "\e[7mDescargando Archivos\e[0m"; sleep 3 ; echo -e "\e[36mDescargando Dropbear\e[36m" && sleep 2;apt-get install dropbear -y
sleep 2 ;echo -e "\e[32mCORRECTO!\e[0m" 
sleep 3 ; echo -e "\e[36mDescargando Python\e[36m" && sleep 2;apt-get install python -y ;apt-get install python2 -y;apt install python-pip -y
sleep 4 ;echo -e "\e[36mDescargando Proxy Abono\e[0m"
sleep 2 ; cd /etc/ARCHIVOSVPS/ ; wget https://raw.githubusercontent.com/nachorivas581/ARCHIVOSVPS/main/Proxypython.py
sleep 3 ; echo ">>>Instalaremos Todo lo necesario Se paciente<<<"
sleep 2 ; wget https://raw.githubusercontent.com/nachorivas581/ARCHIVOSVPS/main/adm ; wget  https://raw.githubusercontent.com/nachorivas581/ARCHIVOSVPS/main/eliminar ; wget  https://raw.githubusercontent.com/nachorivas581/ARCHIVOSVPS/main/expiracion ; wget https://raw.githubusercontent.com/nachorivas581/ARCHIVOSVPS/main/menuuser ; wget https://raw.githubusercontent.com/nachorivas581/ARCHIVOSVPS/main/modificar ; wget https://raw.githubusercontent.com/nachorivas581/ARCHIVOSVPS/main/password ; wget https://raw.githubusercontent.com/nachorivas581/ARCHIVOSVPS/main/rc.local ; wget https://raw.githubusercontent.com/nachorivas581/ARCHIVOSVPS/main/usuarios ; cp adm /usr/local/bin ; cd /usr/local/bin ; chmod u+x adm ; chmod 0750 adm 
sleep 2 ;echo -e "\e[32mCORRECTO!\e[0m
echo  LIBERANDO ARCHIVOS RESIDUALES
sleep 3 ; echo -e "\e[7mEliminando Archivos no necesarios\e[0m" 
sleep 3; echo ">>>Eliminando Instalacion<<<"
sleep 2; echo . ;sleep 2; echo . ;sleep 2; echo . ;sleep 2; echo . ;rm Instalacion ; echo "ELIMINADA CON EXITO"
sleep 3 ;echo -e "\e[7mArchivos Eliminados Con exito\e[0m"
sleep 3 ; echo -e "\e[7mEscribe adm para ejecutar el script! \e[0m" ; cd  
exit
