#!/bin/bash
echo "░██████╗██╗░░██╗░█████╗░██████╗░██╗░░██╗██╗░░░██╗██████╗░░██████╗";
echo "██╔════╝██║░░██║██╔══██╗██╔══██╗██║░██╔╝██║░░░██║██╔══██╗██╔════╝";
echo "╚█████╗░███████║███████║██████╔╝█████═╝░╚██╗░██╔╝██████╔╝╚█████╗░";
echo  "╚═══██╗██╔══██║██╔══██║██╔══██╗██╔═██╗░░╚████╔╝░██╔═══╝░░╚═══██╗";
echo "██████╔╝██║░░██║██║░░██║██║░░██║██║░╚██╗░░╚██╔╝░░██║░░░░░██████╔╝";
echo "╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚═════╝░";


sleep 2 ; echo Recuerda que necesitamos que nos concedas permisos de SuperUsuario para Continuar ;
sleep 2 ; echo -e "\e[91mSi no tienes Dichos Permisos Tendras errores en la instalacion!\e[0m"
sleep 2 ; echo "Muchas Gracias"
sleep 3; echo Estamos actualizando la consola &&
sleep 2;apt update -y ; apt upgrade -y ; apt install nano 

sleep 4 ; echo Espera un momento ;sleep 2; echo . ;sleep 1 ; echo . ; sleep 1 ; echo .; sleep 1  ; echo . ; sleep 3 ;sleep 1  ; echo .
sleep 1 ;echo . ; sleep 1 ; echo "--------------------------------------------------------------------------------------------" ;
sleep 1 ; echo "--------------------------------------------------------------------------------------------"
sleep 1 ; echo "--------------------------------------------------------------------------------------------"
sleep 1 ; echo "--------------------------------------------------------------------------------------------"
sleep 1 ; echo "--------------------------------------------------------------------------------------------"
sleep 1 ; echo "--------------------------------------------------------------------------------------------"
sleep 3;echo -e "\e[32mEXITO!\e[0m" ; 
sleep 3 ; echo -e "\e[106mInstalaremos los archivos necesarios!\e[0m"
sleep 3 ;echo -e "\e[101mBuscando Archivos!\e[0m" ;sleep 1 ;echo . ;sleep 1 ;echo . ;sleep 1 ;echo . ;sleep 1 ;echo . ;sleep 1 ;echo .;sleep 1 ;echo .
sleep 1 ;echo . ;sleep 1 ;echo . ;sleep 1 ;echo . ;sleep 1 ;echo . ;sleep 1 ;echo . ;sleep 1 ;echo .
sleep 3 ;echo -e "\e[7mAccediendo\e[0m";sleep 1 ;echo -e "\e[7m.\e[0m" ; sleep 1 ;echo -e "\e[7m.\e[0m" ; sleep 1 ;echo -e "\e[7m.\e[0m" ; sleep 1 ;echo -e "\e[7m.\e[0m"
sleep 1 ;echo -e "\e[7m.\e[0m"; sleep 1 ;echo -e "\e[7m.\e[0m"; sleep 1 ;echo -e "\e[7m.\e[0m";sleep 1 ;echo -e "\e[7m.\e[0m"; sleep 1 ;echo -e "\e[7m.\e[0m";
sleep 3 ;echo -e "\e[7mPermisos concedidos!\e[0m"
sleep 3 ;echo -e "\e[91mAguarde un Momento\e[0m"
sleep 6 ;echo -e "\e[7mDescargando Archivos\e[0m"; sleep 3 ; echo -e "\e[36mDescargando Dropbear\e[36m" && sleep 2;apt-get install dropbear -y
sleep 2 ;echo -e "\e[32mCORRECTO!\e[0m" 
sleep 3 ; echo -e "\e[36mDescargando Python\e[36m" && sleep 2;apt-get install python -y ;apt-get install python2- y;apt install python-pip
sleep 3 ; echo -e "\e[36mDescargando BADVPN\e[36m" && apt-get install wget && apt install make -y ; apt install cmake -y; wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2 -o /dev/null
sleep 4 ;echo -e "\e[36mComienza La instalacion del Proxy Abono\e[0m"
sleep 2 ; wget https://github.com/nachorivas581/ARCHIVOSVPS/blob/main/Proxypython.py
sleep 3 ; echo -e "\e[32mInstalado Correctamente!\e[0m"
