#!/bin/bash
echo -e      "\e[41m CONSOLA VPS-ARG By :SharkLight\e[0m"

sleep 3 ;echo -e "\e[7mQue deseas hacer?\e[0m"
           select yn in "Modificar Password" "Modificar Fecha de expiracion" "Volver al menu principal" ; do
             case $yn in
                   "Modificar Password") bash password ; clear ; bash modificar;;
                   "Modificar Fecha de expiracion") bash expiracion ; clear ;bash modificar;;
                    "Volver al menu principal") bash adm 
esac
done
