#!/bin/bash
echo -e      "\e[41m CONSOLA VPS-ARG By :SharkLight\e[0m"

echo -e "\e[32mDigite Nombre de usuario VPS:\e[0m"
read Nombre
echo "El usuario Seleccionado es $Nombre"
passwd $Nombre ; echo "Cambio de clave se ejecuto con Exito!" ; exit 
