#!/bin/bash
echo -e "\e[32mDigite Nombre de usuario VPS:\e[0m"
read Nombre
echo "Su nombre es $Nombre"
echo -e "\e[32mDigite Dia (TIPO DD/)duracion:\e[0m"
read $Dia
echo "Dias $Dia"
echo -e "\e[32mDigite Mes (tipo MM/) duracion:\e[0m"
read $Mes
echo "Mes $Mes"
echo -e "\e[32mDigite Ano (tipo /AAAA) duracion:\e[0m"
read $Ano
echo "AÑO $Ano"
adduser - m -e $Dia-$Mes-$Ano $Nombre
